# -*- coding: utf-8 -*-
"""
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten 
pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 
70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference 
are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

Analysis:

1. Generate the list of pantagonal numbers from 1 to 1,000
2. Generate a list where the sum 
    
"""
import time
import itertools
from math_functions import pow_digits

start_time = time.time()
e = 5
L = 9**e * (e-1)

print ("Project Euler 30 Solution =", sum(n for n in range(10, L) if pow_digits(n, e) == n))

elapsed_time = time.time() - start_time
print ("Elapse time: {:.2f} sec".format(elapsed_time))

