# -*- coding: utf-8 -*-
"""
The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

import time
import math 

start_time = time.time()

#Calculate the triangle number
def tn(n):
    sum = 0
    for i in range(0,n+1):
        sum += i
    return sum
    
def factors(x):
    results = set()
    for i in range(1, int(math.sqrt(x)) + 1):
        if x % i == 0:
            results.add(i)
            results.add(int(x/i))
    return results
   
a = 1
n_len = 1
n_array = []
while (n_len < 100) : 
    t_number = tn(a)
    n_array = factors(t_number)
    n_len = len(n_array)
    a += 1

print ("Triangle number {:d} is {:d} and number of factors are: {:d} ".format(a,t_number,n_len))
#print (n_array)

elapsed_time = time.time() - start_time
print ("Elapse time: {:.2f} sec".format(elapsed_time))